"""
File: test_service.py

Purpose:
Adaptive tests - generation, submission and grading.

The frontend has always called POST /instances/{id}/tests and
POST /tests/{id}/submit; neither existed on the backend. This implements them.

"Adaptive" here means the question mix is selected from measured performance:
topics the learner is failing are oversampled, and difficulty is biased toward
where they actually sit, rather than sampling the bank uniformly.

Distractors are drawn from other Q&A pairs in the same instance (preferring
the same topic) instead of being generated by the LLM - it is deterministic,
free, and produces plausible-but-wrong options by construction.
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta
from typing import Dict, List, Optional

from sqlalchemy import Integer, func
from sqlalchemy.orm import Session

from ..models.instance import Instance
from ..models.qa_pair import QAPair
from ..models.review_log import ReviewLog
from ..models.test import Test, TestQuestion

OPTIONS_PER_QUESTION = 4
WEAK_ACCURACY = 0.6


class TestService:
    def __init__(self, db: Session):
        self.db = db

    # ----------------------------------------------------------- generation

    def create_test(self, instance_id: int, count: int = 10) -> Dict:
        """
        Build an adaptive test session.

        Raises:
            ValueError: the instance has no question bank yet.
        """
        bank = (
            self.db.query(QAPair).filter(QAPair.instance_id == instance_id).all()
        )
        if not bank:
            raise ValueError(
                "No questions available. Generate flashcards for this instance first."
            )

        count = max(1, min(count, len(bank)))
        weak_topics = self._weak_topics(instance_id)
        selected = self._select_questions(bank, count, weak_topics)

        strategy = "adaptive:weak-topics" if weak_topics else "adaptive:baseline"
        test = Test(
            instance_id=instance_id,
            question_count=len(selected),
            strategy=strategy,
        )
        self.db.add(test)
        self.db.flush()

        for position, qa_pair in enumerate(selected):
            options, correct_index = self._build_options(qa_pair, bank)
            self.db.add(
                TestQuestion(
                    test_id=test.id,
                    qa_pair_id=qa_pair.id,
                    position=position,
                    question=qa_pair.question,
                    options=options,
                    correct_index=correct_index,
                    topic=qa_pair.topic,
                    difficulty=qa_pair.difficulty,
                )
            )

        self.db.commit()
        self.db.refresh(test)

        return self.present_test(test, include_answers=False)

    def _weak_topics(self, instance_id: int) -> List[str]:
        cutoff = datetime.utcnow() - timedelta(days=60)
        rows = (
            self.db.query(
                ReviewLog.topic,
                func.count(ReviewLog.id),
                func.sum(func.cast(ReviewLog.correct, Integer)),
            )
            .filter(
                ReviewLog.instance_id == instance_id,
                ReviewLog.reviewed_at >= cutoff,
                ReviewLog.topic.isnot(None),
            )
            .group_by(ReviewLog.topic)
            .all()
        )

        weak = []
        for topic, reviews, correct in rows:
            reviews = int(reviews or 0)
            if reviews < 2:
                continue
            if int(correct or 0) / reviews < WEAK_ACCURACY:
                weak.append(topic)

        return weak

    def _select_questions(
        self, bank: List[QAPair], count: int, weak_topics: List[str]
    ) -> List[QAPair]:
        """
        Oversample weak topics (~60% of the paper) while keeping coverage.
        """
        if not weak_topics:
            return random.sample(bank, count)

        weak_pool = [qa for qa in bank if qa.topic in weak_topics]
        rest_pool = [qa for qa in bank if qa.topic not in weak_topics]

        weak_target = min(len(weak_pool), int(round(count * 0.6)))
        selected = random.sample(weak_pool, weak_target) if weak_target else []

        remaining = count - len(selected)
        if remaining > 0:
            fill_pool = rest_pool or [qa for qa in weak_pool if qa not in selected]
            selected.extend(random.sample(fill_pool, min(remaining, len(fill_pool))))

        # Still short (tiny bank)? Top up from whatever is left.
        if len(selected) < count:
            leftovers = [qa for qa in bank if qa not in selected]
            selected.extend(random.sample(leftovers, min(count - len(selected), len(leftovers))))

        random.shuffle(selected)
        return selected[:count]

    def _build_options(self, qa_pair: QAPair, bank: List[QAPair]) -> tuple[List[str], int]:
        """
        Build MCQ options: the real answer plus distractors from other cards.

        Same-topic answers are preferred - a distractor from an unrelated topic
        is trivially eliminable and makes the test measure nothing.
        """
        correct = qa_pair.answer.strip()

        same_topic = [
            qa.answer.strip()
            for qa in bank
            if qa.id != qa_pair.id
            and qa.topic == qa_pair.topic
            and qa.answer.strip() != correct
        ]
        other = [
            qa.answer.strip()
            for qa in bank
            if qa.id != qa_pair.id
            and qa.topic != qa_pair.topic
            and qa.answer.strip() != correct
        ]

        random.shuffle(same_topic)
        random.shuffle(other)

        distractors: List[str] = []
        for candidate in same_topic + other:
            if candidate in distractors:
                continue
            distractors.append(candidate)
            if len(distractors) == OPTIONS_PER_QUESTION - 1:
                break

        options = [correct] + distractors
        random.shuffle(options)
        return options, options.index(correct)

    # ----------------------------------------------------------- submission

    def submit_test(self, test_id: int, answers: Dict) -> Optional[Dict]:
        """
        Grade a submission.

        `answers` maps question id (or position) -> selected option index.
        Both keys are accepted because the frontend indexes by position.
        """
        test = self.db.query(Test).filter(Test.id == test_id).first()
        if not test:
            return None

        normalized = {str(key): value for key, value in (answers or {}).items()}
        correct_count = 0

        for question in test.questions:
            raw = normalized.get(str(question.id))
            if raw is None:
                raw = normalized.get(str(question.position))

            selected = self._coerce_index(raw)
            question.selected_index = selected
            question.is_correct = selected is not None and selected == question.correct_index
            if question.is_correct:
                correct_count += 1

        total = len(test.questions)
        test.correct_count = correct_count
        test.score = round(correct_count / total * 100, 1) if total else 0.0
        test.completed_at = datetime.utcnow()

        # Surface the latest score on the instance for the dashboard card.
        instance = self.db.query(Instance).filter(Instance.id == test.instance_id).first()
        if instance:
            instance.last_score = test.score

        self.db.commit()
        self.db.refresh(test)

        return self.present_test(test, include_answers=True)

    @staticmethod
    def _coerce_index(value) -> Optional[int]:
        if value is None or value == "":
            return None
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    # -------------------------------------------------------------- reading

    def get_test(self, test_id: int, include_answers: bool = False) -> Optional[Dict]:
        test = self.db.query(Test).filter(Test.id == test_id).first()
        if not test:
            return None
        return self.present_test(test, include_answers=include_answers)

    def list_tests(self, instance_id: int) -> List[Dict]:
        rows = (
            self.db.query(Test)
            .filter(Test.instance_id == instance_id)
            .order_by(Test.created_at.desc())
            .all()
        )
        return [
            {
                "id": test.id,
                "question_count": test.question_count,
                "score": test.score,
                "strategy": test.strategy,
                "created_at": test.created_at.isoformat() if test.created_at else None,
                "completed_at": test.completed_at.isoformat() if test.completed_at else None,
            }
            for test in rows
        ]

    def present_test(self, test: Test, include_answers: bool) -> Dict:
        questions = []
        for question in test.questions:
            payload = {
                "id": question.id,
                "position": question.position,
                "question": question.question,
                "options": question.options or [],
                "topic": question.topic,
                "difficulty": question.difficulty,
            }
            if include_answers:
                payload["correct"] = question.correct_index
                payload["selected"] = question.selected_index
                payload["is_correct"] = question.is_correct
            questions.append(payload)

        return {
            "id": test.id,
            "instance_id": test.instance_id,
            "question_count": test.question_count,
            "strategy": test.strategy,
            "score": test.score,
            "correct_count": test.correct_count,
            "created_at": test.created_at.isoformat() if test.created_at else None,
            "completed_at": test.completed_at.isoformat() if test.completed_at else None,
            "questions": questions,
        }
